=== ohadschn/ET4W/src/events-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://github.com/ohadschn/ET4W/src/events-schema.json",

  "definitions": {
    "identifier": {
      "type": "string",
      "pattern": "^([a-zA-Z_][a-zA-Z0-9-_]*)*$"
    },
    "identifier-array": {
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "#/definitions/identifier" }
    },
    "parameter": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/definitions/identifier" },
        "type": { "enum": [ "Boolean", "Char", "SByte", "Byte", "Int16", "UInt16", "Int32", "UInt32", "Int64", "UInt64", "Single", "Double", "DateTime", "String", "GUID", "IntPtr", "ByteArray" ] }
      },
      "required": [ "name", "type" ]
    },
    "parameter-array": {
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "#/definitions/parameter" }
    },
    "event": {
      "type": "object",
      "properties": {
        "id": { "type": "integer" },
        "name": { "$ref": "#/definitions/identifier" },
        "level": { "enum": [ "Verbose", "Informational", "Warning", "Error", "Critical", "LogAlways" ] },
        "message": { "type": "string" },
        "keywords": { "$ref": "#/definitions/identifier-array" },
        "task": { "$ref": "#/definitions/identifier" },
        "opcode": { "enum": [ "Info", "Start", "Stop", "DataCollectionStart", "DataCollectionStop", "Extension", "Reply", "Resume", "Suspend", "Send", "Receive" ] },
        "parameters": { "$ref": "#/definitions/parameter-array" }
      },
      "required": [
        "id",
        "name"
      ]
    }
  },

  "type": "object",
  "properties": {
    "class": { "$ref": "#/definitions/identifier" },
    "sourceName": { "type": "string" },
    "tasks": { "$ref": "#/definitions/identifier-array" },
    "keywords": {
      "allOf": [
        { "$ref": "#/definitions/identifier-array" },
        { "maxItems": 44 }
      ]
    },
    "events": {
      "type": "array",
      "items": { "$ref": "#/definitions/event" }
    }
  },
  "required": [
    "class",
    "sourceName",
    "events"
  ]
}

=== ohadschn/ET4W/src/Tests/EventSources/events.json
{
  "$schema": "../../events-schema.json",
  "class": "Tests",
  "sourceName": "OS-Test-Foo",
  "tasks": [ "Foo", "Boo" ],
  "keywords": [ "Baz", "Faz", "Raz" ],
  "events": [
    {
      "id": 1,
      "name": "NoKeyWords",
      "level": "Informational",
      "message": "Event with no keywords",
      "task": "Foo",
      "opcode": "Info"
    },
    {
      "id": 2,
      "name": "NoTask",
      "level": "Warning",
      "message": "Event with no task",
      "keywords": [ "Raz" ],
      "opcode": "Info"
    },
    {
      "id": 3,
      "name": "NoOpcode",
      "level": "Error",
      "message": "Event with no Opcode",
      "keywords": [ "Baz", "Faz" ],
      "task": "Boo"
    }
  ]
}

=== ohadschn/ET4W/src/Tests/Events/SampleEvents.json
{
    "$schema": "ET4W/events-schema.json",
    "class": "Sample",
    "sourceName": "OS-Samples",
    "tasks": ["Measure"],
    "keywords": ["Key","Word"],
    "events": [
      {
        "id": 1,
        "name": "MeasureStart",
        "keywords": ["Key", "Word"],
        "task": "Measure",
        "message": "foo: {0}",
        "parameters": [
          {
            "name": "foo",
            "type": "Int32"
          }
        ]
      }
    ]
  }
